version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: web-ext
    versions:
    - 5.5.0
    - 6.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
